#!name=Spotify Premium

#!desc=Tunaa

# Partially unlock premium, recommend re-logging, sound quality cannot be set to ultra-high

# 1. In the search interface, playlists/songs can be freely switched and played in full. 2. In the music library, liked songs can be freely switched and played in full.

[MITM]
hostname = %APPEND% spclient.wg.spotify.com

[Script]
spotify-json = type=http-request,type=http-request,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/Tunaa-11342/Testing101/refs/heads/main/js/spotify-json.js
spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js,script-update-interval=0
